### ISSUE TITLE
Vagrant unpacking fails

### ISSUE THREAD

**Issue by BartTiemersma** [openwisp/vagrant-openwisp2#10]
After running `vagrant up`, I'm getting the following output:

Bringing machine &apos;openwisp2&apos; up with &apos;virtualbox&apos; provider...
<b>==&gt; openwisp2: Box &apos;debian/buster64&apos; could not be found. Attempting to find and install...</b>
    openwisp2: Box Provider: virtualbox
    openwisp2: Box Version: &gt;= 0
<b>==&gt; openwisp2: Loading metadata for box &apos;debian/buster64&apos;</b>
    openwisp2: URL: https://vagrantcloud.com/debian/buster64
<b>==&gt; openwisp2: Adding box &apos;debian/buster64&apos; (v10.3.0) for provider: virtualbox</b>
    openwisp2: Downloading: https://vagrantcloud.com/debian/boxes/buster64/versions/10.3.0/providers/virtualbox.box
#&lt;Thread:0x000055fe52a5d448@/usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/batch_action.rb:71 run&gt; terminated with exception (report_on_exception is true):
<b>Traceback</b> (most recent call last):
	39: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run&apos;
	38: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:188:in `action&apos;
	37: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:188:in `call&apos;
	36: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/environment.rb:592:in `lock&apos;
	35: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:202:in `block in action&apos;
	34: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:227:in `action_raw&apos;
	33: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `run&apos;
	32: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/util/busy.rb:19:in `busy&apos;
	31: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `block in run&apos;
	30: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builder.rb:116:in `call&apos;
	29: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call&apos;
	28: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call&apos;
	27: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call&apos;
	26: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/call.rb:53:in `call&apos;
	25: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `run&apos;
	24: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/util/busy.rb:19:in `busy&apos;
	23: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `block in run&apos;
	22: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builder.rb:116:in `call&apos;
	21: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call&apos;
	20: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action&apos;
	19: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call&apos;
	18: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/handle_box.rb:36:in `call&apos;
	17: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/handle_box.rb:36:in `synchronize&apos;
	16: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/handle_box.rb:42:in `block in call&apos;
	15: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/handle_box.rb:82:in `handle_box&apos;
	14: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `run&apos;
	13: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/util/busy.rb:19:in `busy&apos;
	12: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `block in run&apos;
	11: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builder.rb:116:in `call&apos;
	10: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call&apos;
	 9: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/box_add.rb:118:in `call&apos;
	 8: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/box_add.rb:283:in `add_from_metadata&apos;
	 7: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/box_add.rb:357:in `box_add&apos;
	 6: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/box_collection.rb:104:in `add&apos;
	 5: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/box_collection.rb:447:in `with_collection_lock&apos;
	 4: from /usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize&apos;
	 3: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/box_collection.rb:448:in `block in with_collection_lock&apos;
	 2: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/box_collection.rb:115:in `block in add&apos;
	 1: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/box_collection.rb:461:in `with_temp_dir&apos;
/usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/box_collection.rb:121:in `block (2 levels) in add&apos;: <b>The box failed to unpackage properly. Please verify that the box (</b><u style="text-decoration-style:single"><b>Vagrant::Errors::BoxUnpackageFailure</b></u><b>)</b>
<b>file you&apos;re trying to add is not corrupted and that enough disk space</b>
<b>is available and then try again.</b>
<b>The output from attempting to unpackage (if any):</b>

<b>x ./metadata.json</b>
<b>x ./box.ovf</b>
<b>x ./buster.vmdk: Write failed</b>
<b>x ./Vagrantfile: Write failed</b>
<b>bsdtar: Error exit delayed from previous errors.</b></pre>

**Comment by nemesisdesign** [comment]
How much disk space you have left?

**Comment by BartTiemersma** [comment]
I was trying to run it from a Ubuntu live USB stick. I think the filesystem was to blame (fat32), rather than the amount of available disk space (clean image on a 64GB stick). Instead, I'm now running a full installation of Ubuntu from the stick and got it to work!

By the way, I didn't have much luck with either the Windows subsystem for Linux or VirtualBox on Windows, so that's why I'm trying to run it from a stick now.

Thanks for the help!

**Comment by nemesisdesign** [comment]
Thanks for updating the issue.
