### ISSUE TITLE
Hello , i have a problem

### ISSUE THREAD

**Issue by JoxtaQrst** [openwisp/vagrant-openwisp2#5]
I followed the steps and installed everything, but when I wrote the command "vagrant up" it shows this error, can i do something about it?
![screenshot from 2018-11-03 18-32-37](https://user-images.githubusercontent.com/44101553/48020335-5e3bcf00-e13e-11e8-9d3d-b63a83e32a40.png)

**Comment by nemesisdesign** [comment]
@JoxtaQrst please post to this issue #4
