### ISSUE TITLE
Vagrant issue in task  Install openwisp2 controller

### ISSUE THREAD

**Issue by kboghdady** [openwisp/vagrant-openwisp2#7]
I have been having this issue while installing the vagrant VM 
TASK [openwisp.openwisp2 : Install openwisp2 controller and its dependencies] ***
FAILED - RETRYING: Install openwisp2 controller and its dependencies (5 retries left).
FAILED - RETRYING: Install openwisp2 controller and its dependencies (4 retries left).
FAILED - RETRYING: Install openwisp2 controller and its dependencies (3 retries left).
FAILED - RETRYING: Install openwisp2 controller and its dependencies (2 retries left).
FAILED - RETRYING: Install openwisp2 controller and its dependencies (1 retries left).

fatal: [192.168.56.5]: FAILED! => {"attempts": 5, "changed": false, "cmd": ["/opt/openwisp2/env/bin/pip", "install", "-U", "openwisp-controller~=0.4", "channels_redis", "service_identity"], "msg": "stdout: Collecting openwisp-controller~=0.4\n  Using cached openwisp_controller-0.5-py2.py3-none-any.whl (97 kB)\nCollecting channels_redis\n  Using cached channels_redis-2.3.2-py2.py3-none-any.whl (13 kB)\nCollecting service_identity\n  Using cached service_identity-18.1.0-py2.py3-none-any.whl (11 kB)\nCollecting openwisp-utils<0.5.0,>=0.4.2\n  Using cached openwisp_utils-0.4.3-py2.py3-none-any.whl (72 kB)\nCollecting djangorestframework-gis<0.16.0,>=0.12.0\n  Using cached djangorestframework_gis-0.15-py2.py3-none-any.whl (18 kB)\nCollecting paramiko<2.8.0,>=2.4.1\n  Using cached paramiko-2.7.1-py2.py3-none-any.whl (206 kB)\nCollecting celery<4.5.0,>=4.2.0\n  Using cached celery-4.4.0-py2.py3-none-any.whl (421 kB)\nCollecting django-netjsonconfig<0.11.0,>=0.10.0\n  Using cached django_netjsonconfig-0.10.1-py2.py3-none-any.whl (402 kB)\nCollecting openwisp-users<0.3.0,>=0.2.0\n  Using cached openwisp_users-0.2.0-py2.py3-none-any.whl (29 kB)\nCollecting django-loci<0.4.0,>=0.3.1\n  Using cached django_loci-0.3.1-py2.py3-none-any.whl (38 kB)\nCollecting scp<0.14.0,>=0.13.0\n  Using cached scp-0.13.2-py2.py3-none-any.whl (9.5 kB)\nCollecting asgiref~=2.1\n  Using cached asgiref-2.3.2-py2.py3-none-any.whl (9.3 kB)\nCollecting aioredis~=1.0\n  Using cached aioredis-1.3.1-py3-none-any.whl (65 kB)\nCollecting msgpack~=0.5.2\n  Using cached msgpack-0.5.6-cp35-cp35m-manylinux1_x86_64.whl (309 kB)\nCollecting channels~=2.0\n  Using cached channels-2.4.0-py2.py3-none-any.whl (37 kB)\nRequirement already satisfied, skipping upgrade: pyasn1 in /usr/lib/python3/dist-packages (from service_identity) (0.1.9)\nRequirement already satisfied, skipping upgrade: cryptography in /opt/openwisp2/env/lib/python3.5/site-packages (from service_identity) (2.8)\nCollecting attrs>=16.0.0\n  Using cached attrs-19.3.0-py2.py3-none-any.whl (39 kB)\nCollecting pyasn1-modules\n  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)\nCollecting django-model-utils<4.1.0,>=4.0.0\n  Using cached django_model_utils-4.0.0-py2.py3-none-any.whl (29 kB)\nCollecting djangorestframework\n  Using cached djangorestframework-3.11.0-py3-none-any.whl (911 kB)\nCollecting pynacl>=1.0.1\n  Using cached PyNaCl-1.3.0-cp34-abi3-manylinux1_x86_64.whl (759 kB)\nCollecting bcrypt>=3.1.3\n  Using cached bcrypt-3.1.7-cp34-abi3-manylinux1_x86_64.whl (56 kB)\nCollecting kombu<4.7,>=4.6.7\n  Using cached kombu-4.6.7-py2.py3-none-any.whl (182 kB)\nCollecting pytz>dev\n  Using cached pytz-2019.3-py2.py3-none-any.whl (509 kB)\nCollecting vine==1.3.0\n  Using cached vine-1.3.0-py2.py3-none-any.whl (14 kB)\nCollecting billiard<4.0,>=3.6.1\n  Using cached billiard-3.6.3.0-py3-none-any.whl (89 kB)\nCollecting django-sortedm2m<3.1.0,>=3.0.0\n  Using cached django_sortedm2m-3.0.0-py2.py3-none-any.whl (34 kB)\nCollecting django-taggit<1.3.0,>=0.24.0\n  Using cached django_taggit-1.2.0-py3-none-any.whl (45 kB)\nCollecting netjsonconfig<0.8.0,>=0.7.0\n  Using cached netjsonconfig-0.7-py2.py3-none-any.whl (76 kB)\nCollecting django-x509<0.7.0,>=0.6.1\n  Using cached django_x509-0.6.2-py2.py3-none-any.whl (43 kB)\nCollecting jsonfield2<4.0.0,>=3.1.0\n  Using cached jsonfield2-3.1.0-py3-none-any.whl (6.4 kB)\nCollecting django<3.1,>=2.2\n  Using cached Django-2.2.10-py3-none-any.whl (7.5 MB)\nCollecting django-reversion<3.1.0,>=3.0.5\n  Using cached django_reversion-3.0.5-py2.py3-none-any.whl (80 kB)\nCollecting django-allauth<0.42.0,>=0.39.0\n  Using cached django-allauth-0.41.0.tar.gz (545 kB)\nCollecting django-organizations<1.2.0,>=1.0.0\n  Using cached django_organizations-1.1.2-py2.py3-none-any.whl (56 kB)\nCollecting django-extensions<2.3,>=1.7.5\n  Using cached django_extensions-2.2.8-py2.py3-none-any.whl (224 kB)\nCollecting packaging\n  Using cached packaging-20.1-py2.py3-none-any.whl (36 kB)\nCollecting django-phonenumber-field<4.1.0,>=2.4.0\n  Using cached django_phonenumber_field-4.0.0-py3-none-any.whl (51 kB)\nCollecting phonenumbers<8.12.0,>=8.11.0\n  Using cached phonenumbers-8.11.4-py2.py3-none-any.whl (2.6 MB)\nCollecting django-leaflet<0.27,>=0.23\n  Using cached django-leaflet-0.26.0.tar.gz (282 kB)\nCollecting Pillow<=7.1.0,>=6.2.0\n  Using cached Pillow-7.0.0-cp35-cp35m-manylinux1_x86_64.whl (2.1 MB)\nCollecting async-timeout<4.0,>=2.0\n  Using cached async_timeout-3.0.1-py3-none-any.whl (8.2 kB)\nCollecting hiredis\n  Using cached hiredis-1.0.1-cp35-cp35m-manylinux2010_x86_64.whl (59 kB)\nCollecting daphne~=2.3\n  Using cached daphne-2.4.1-py2.py3-none-any.whl (25 kB)\nRequirement already satisfied, skipping upgrade: cffi!=1.11.3,>=1.8 in /opt/openwisp2/env/lib/python3.5/site-packages (from cryptography->service_identity) (1.14.0)\nRequirement already satisfied, skipping upgrade: six>=1.4.1 in /usr/lib/python3/dist-packages (from cryptography->service_identity) (1.10.0)\nCollecting amqp<2.6,>=2.5.2\n  Using cached amqp-2.5.2-py2.py3-none-any.whl (49 kB)\nCollecting importlib-metadata>=0.18; python_version < \"3.8\"\n  Using cached importlib_metadata-1.5.0-py2.py3-none-any.whl (30 kB)\nCollecting jinja2<3.0,>=2.9\n  Using cached Jinja2-2.11.1-py2.py3-none-any.whl (126 kB)\nCollecting jsonschema<3.3,>=3.0\n  Using cached jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)\n\n:stderr: ERROR: Could not find a version that satisfies the requirement jsonfield<4.0.0,>=3.1.0 (from django-x509<0.7.0,>=0.6.1->django-netjsonconfig<0.11.0,>=0.10.0->openwisp-controller~=0.4) (from versions: 0.7, 0.8, 0.9, 0.9.2, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 0.9.8, 0.9.9, 0.9.10, 0.9.11, 0.9.12, 0.9.13, 0.9.14, 0.9.15, 0.9.17, 0.9.18, 0.9.19, 0.9.20, 0.9.22, 0.9.23, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1, 3.0.0)\nERROR: No matching distribution found for jsonfield<4.0.0,>=3.1.0 (from django-x509<0.7.0,>=0.6.1->django-netjsonconfig<0.11.0,>=0.10.0->openwisp-controller~=0.4)\n"}

**Comment by nemesisdesign** [comment]
Thanks for reporting, it looks like it's happening also in the build of ansible-openwisp2:
https://travis-ci.org/openwisp/ansible-openwisp2/builds/655842134

On what distribution are you testing?

**Comment by kboghdady** [comment]
yeah that what I am testing

**Comment by nemesisdesign** [comment]
I'm currently testing #8 to see if it fixes the issue.

**Comment by nemesisdesign** [comment]
Fixed, destroy the debian9 base VM and re-create it with debian10 please.
