### ISSUE TITLE
ubuntu18 install error

### ISSUE THREAD

**Issue by kapook007** [openwisp/vagrant-openwisp2#9]
xxx@www:~/openwisp2-ansible-playbook$ ansible-playbook -i hosts playbook.yml -u root -k --become
SSH password:

PLAY [openwisp2] *****************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************
fatal: [192.168.1.143]: FAILED! => {"msg": "Using a SSH password instead of a key is not possible because Host Key checking is enabled and sshpass does not support this.  Please add this host's fingerprint to your known_hosts file to manage this host."}

PLAY RECAP ***********************************************************************************************************************************************************
192.168.1.143              : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

xxx@www:~/openwisp2-ansible-playbook$

**Comment by nemesisdesign** [comment]
I don't understand. This project [uses debian buster (10) to provide the automatic provisioning](https://github.com/openwisp/vagrant-openwisp2/blob/1a2e3999863e303595b95b10f0e9095e8a7e676c/Vagrantfile#L7), what does ubuntu18 have to do with it?

**Comment by nemesisdesign** [comment]
Closing because report is not clear. If you need support, use the [OpenWISP support channels](http://openwisp.org/support.html).
